### ISSUE TITLE
repos without master branches (develop only) doesn't seem to clone

### ISSUE THREAD

**Issue by shleeable** [devCharles/gitRepoUpdater#1]
I've got a few repos with 1 branch called develop (no master).. this seems to be empty until I checkout develop and pull

**Comment by devCharles** [comment]
Oh, I haven't considered a repo without a master branch, let me check that case and complete the script, thanks for contributing ;)

**Comment by cybershambles** [comment]
Thanks for the assistance.

**Comment by devCharles** [comment]
bro in which option do you have problems? usning "-e" flag or using "-a" or what is the way that you get your repo not updated? becuase i am using `gitRepoUpdater -a` and i dont have problems with the repos with only a develop branch, but when i use `gitRepoUpdater -e` i found a bug when you answer "yes" in the repo
